### ISSUE TITLE
Error messages while getting options

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-woocommerce#89]
I got these error messages while viewing a post.

`Warning: Invalid argument supplied for foreach() in /srv/www/wordpress-develop/src/wp-content/plugins/wordpress-seo/inc/options/class-wpseo-options.php on line 152`

`Notice: Undefined index: breadcrumbs-enable in /srv/www/wordpress-develop/src/wp-content/plugins/wpseo-woocommerce/wpseo-woocommerce.php on line 124`

Something similar happend in Video SEO:
https://github.com/Yoast/wpseo-video/pull/214

Easily fixable by calling WPSEO_Options::get_instance() before retrieving any options. However, we might want to solve this using a different approach.

**Comment by boblinthorst** [comment]
Couldn't reproduce. In the referenced issue (Yoast/wpseo-video#214), you mentioned 'fixed in another pull', was this a wpseo_video specific pull? If so, could it have also fixed this issue?

If this is the case, please close this issue. Otherwise, could you try to be a bit more specific as to how this issue can be reproduced?

**Comment by diedexx** [comment]
I _think_ this issue still occurs by looking at some code. However, I have not been able to test it yet.
When WooCommerce isn't installed and the user is on the frontend, [this](https://github.com/Yoast/wpseo-woocommerce/blob/ca6bf6a1016ccab522c4a03f2e2a7f162cbbea76/wpseo-woocommerce.php#L108-L109) code is executed.
`$wpseo_options = WPSEO_Options::get_all();` retruns a list with all options. The option we need, `breadcrumbs-enable`, can probably be found in `$wpseo_options['wpseo_internallinks']['breadcrumbs_enable']
However, instead of using all options, we seem to only need one; `wpseo_internallinks`. `wpseo_internallinks` houses the `breadcrumbs-enable` option WooSEO is trying to use [here](https://github.com/Yoast/wpseo-woocommerce/blob/ca6bf6a1016ccab522c4a03f2e2a7f162cbbea76/wpseo-woocommerce.php#L129).

I suggest trying to replace `$wpseo_options = WPSEO_Options::get_all();` with `$wpseo_options = WPSEO_Options::get_option( 'wpseo_internallinks' );` However, before you can all `get_option`, I _think_ you need to call `WPSEO_Option::get_instance()` first.

**Comment by CarolineGeven** [comment]
Closing this as I can't reproduce. If it still is an issue, please let me know how to reproduce.
